server.port=8084

#eureka.client.enabled=fal

#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:postgresql://localhost:5432/ecom_users
#spring.datasource.username=postgres
#spring.datasource.password=root

#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone=http://localhost:8086/eureka/